//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class MapServiceResponse : Message
    {
        public const string k_RosMessageName = "simulation_srvs/MapService";
        public override string RosMessageName => k_RosMessageName;

        public MapMsg map;

        public MapServiceResponse()
        {
            this.map = new MapMsg();
        }

        public MapServiceResponse(MapMsg map)
        {
            this.map = map;
        }

        public static MapServiceResponse Deserialize(MessageDeserializer deserializer) => new MapServiceResponse(deserializer);

        private MapServiceResponse(MessageDeserializer deserializer)
        {
            this.map = MapMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map);
        }

        public override string ToString()
        {
            return "MapServiceResponse: " +
            "\nmap: " + map.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
