//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class MapServiceRequest : Message
    {
        public const string k_RosMessageName = "simulation_srvs/MapService";
        public override string RosMessageName => k_RosMessageName;


        public MapServiceRequest()
        {
        }
        public static MapServiceRequest Deserialize(MessageDeserializer deserializer) => new MapServiceRequest(deserializer);

        private MapServiceRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "MapServiceRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
