//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class PausePlayResponse : Message
    {
        public const string k_RosMessageName = "simulation_msgs/PausePlay";
        public override string RosMessageName => k_RosMessageName;

        //  Response
        public bool success;
        //  Indique si la demande a réussi ou non
        public string message;
        //  Message d'information ou d'erreur

        public PausePlayResponse()
        {
            this.success = false;
            this.message = "";
        }

        public PausePlayResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static PausePlayResponse Deserialize(MessageDeserializer deserializer) => new PausePlayResponse(deserializer);

        private PausePlayResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "PausePlayResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
