//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class PausePlayRequest : Message
    {
        public const string k_RosMessageName = "simulation_msgs/PausePlay";
        public override string RosMessageName => k_RosMessageName;

        //  Request
        public bool play;

        public PausePlayRequest()
        {
            this.play = false;
        }

        public PausePlayRequest(bool play)
        {
            this.play = play;
        }

        public static PausePlayRequest Deserialize(MessageDeserializer deserializer) => new PausePlayRequest(deserializer);

        private PausePlayRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.play);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.play);
        }

        public override string ToString()
        {
            return "PausePlayRequest: " +
            "\nplay: " + play.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
