//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class ResetRequest : Message
    {
        public const string k_RosMessageName = "simulation_msgs/Reset";
        public override string RosMessageName => k_RosMessageName;

        //  Request
        public string dataset;
        public int min_human;
        public int max_human;

        public ResetRequest()
        {
            this.dataset = "";
            this.min_human = 0;
            this.max_human = 0;
        }

        public ResetRequest(string dataset, int min_human, int max_human)
        {
            this.dataset = dataset;
            this.min_human = min_human;
            this.max_human = max_human;
        }

        public static ResetRequest Deserialize(MessageDeserializer deserializer) => new ResetRequest(deserializer);

        private ResetRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dataset);
            deserializer.Read(out this.min_human);
            deserializer.Read(out this.max_human);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.dataset);
            serializer.Write(this.min_human);
            serializer.Write(this.max_human);
        }

        public override string ToString()
        {
            return "ResetRequest: " +
            "\ndataset: " + dataset.ToString() +
            "\nmin_human: " + min_human.ToString() +
            "\nmax_human: " + max_human.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
