//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class ResetResponse : Message
    {
        public const string k_RosMessageName = "simulation_msgs/Reset";
        public override string RosMessageName => k_RosMessageName;

        //  Response
        public bool success;
        public float distance_start_goal;

        public ResetResponse()
        {
            this.success = false;
            this.distance_start_goal = 0.0f;
        }

        public ResetResponse(bool success, float distance_start_goal)
        {
            this.success = success;
            this.distance_start_goal = distance_start_goal;
        }

        public static ResetResponse Deserialize(MessageDeserializer deserializer) => new ResetResponse(deserializer);

        private ResetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.distance_start_goal);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.distance_start_goal);
        }

        public override string ToString()
        {
            return "ResetResponse: " +
            "\nsuccess: " + success.ToString() +
            "\ndistance_start_goal: " + distance_start_goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
