//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class TriggerRequest : Message
    {
        public const string k_RosMessageName = "simulation_msgs/Trigger";
        public override string RosMessageName => k_RosMessageName;

        //  Request (vide)

        public TriggerRequest()
        {
        }
        public static TriggerRequest Deserialize(MessageDeserializer deserializer) => new TriggerRequest(deserializer);

        private TriggerRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "TriggerRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
