//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Simulation
{
    [Serializable]
    public class MapMsg : Message
    {
        public const string k_RosMessageName = "simulation_msgs/Map";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  The map resolution [m/cell]
        public float resolution;
        //  Map width [cells]
        public uint width;
        //  Map height [cells]
        public uint height;
        //  The origin of the map [m, m, rad]. This is the real-world pose of the
        //  bottom left corner of cell (0,0) in the map.
        public Geometry.PoseMsg origin;
        //  The map data, in row-major order, starting with (0,0).
        //  Cell (1, 0) will be listed second, representing the next cell in the x direction.
        //  Cell (0, 1) will be at the index equal to info.width, followed by (1, 1).
        //  The values inside are application dependent, but frequently,
        //  0 represents unoccupied, 1 represents definitely occupied, and
        //  -1 represents unknown.
        public sbyte[] data;

        public MapMsg()
        {
            this.header = new Std.HeaderMsg();
            this.resolution = 0.0f;
            this.width = 0;
            this.height = 0;
            this.origin = new Geometry.PoseMsg();
            this.data = new sbyte[0];
        }

        public MapMsg(Std.HeaderMsg header, float resolution, uint width, uint height, Geometry.PoseMsg origin, sbyte[] data)
        {
            this.header = header;
            this.resolution = resolution;
            this.width = width;
            this.height = height;
            this.origin = origin;
            this.data = data;
        }

        public static MapMsg Deserialize(MessageDeserializer deserializer) => new MapMsg(deserializer);

        private MapMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.resolution);
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            this.origin = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(sbyte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.resolution);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.origin);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "MapMsg: " +
            "\nheader: " + header.ToString() +
            "\nresolution: " + resolution.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\norigin: " + origin.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
