scenario_info:
  name: Default
  type: Custom
  description: Default minimal scenario
  version: 1.0
  author: RobotSNAP
  created: "2026-09-11 15:11"
  tags:
  - Basic
  - Corner
  - Corridor
  - Indoor
  map: basic/corner
  location: null
  dataset: null
  preview: corner.png
  robot_type: TurtleBot4
  duration: 0
points:
  start_robot:
    x: 9.43463
    y: 0
    z: 0.04240322
    yaw: -90
    center: null
    size: null
  end_robot:
    x: -0.02120304
    y: 0
    z: -9.498233
    yaw: null
    center: null
    size: null
  spawn_zone:
    x: null
    y: null
    z: null
    yaw: null
    center:
      x: 0
      y: 0
      z: -9
    size:
      x: 1
      y: 1
      z: 1
  end_zone:
    x: null
    y: null
    z: null
    yaw: null
    center:
      x: 9
      y: 0
      z: 0
    size:
      x: 1
      y: 1
      z: 1
  pedestrians_start:
    x: 0.02120233
    y: 0
    z: -9.455832
    yaw: null
    center: null
    size: null
  pedestrians_goal_1:
    x: 9.477033
    y: 0
    z: 0.1272097
    yaw: null
    center: null
    size: null
robot:
  start: start_robot
  goal: end_robot
  waypoints: null
  behavior: normal
  speed: 1.2
humans:
- id: pedestrians
  count: 1
  spawn:
    type: point
    ref: pedestrians_start
    position: null
    zone: null
    formation: null
    spacing: 0
    relative_to: null
  goal:
    type: point
    ref: pedestrians_goal_1
    position: null
    zone: null
    target: null
    radius: 0
  goals: null
  movement_controller:
    type: SFM
    onnx_model: null
    sfm_params: null
    hybrid_weights: null
  behavior: normal
  speed: 1
  color: null
  personality: null
